shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - "tinyexec"

allowBuilds:
  esbuild: false
  sharp: false
  simple-git-hooks: true
  vue-demi: false

minimumReleaseAgeExclude:
  - dayjs@1.11.21
